### ISSUE TITLE
integrate ipython notebook into docs

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysisTutorial#1]
Currently, `notebooks/`[MDAnalysisTutorial.ipynb](http://nbviewer.ipython.org/github/MDAnalysis/MDAnalysisTutorial/blob/master/notebooks/MDAnalysisTutorial.ipynb) is only linked from the README but it should also prominently feature in the [introduction of the tutorial](http://www.mdanalysis.org/MDAnalysisTutorial).

**Comment by tylerjereddy** [comment]
Also worth noting that this (and all) ipynb files are now rendered nicely on github. I suppose we could take advantage of this moving forward in some cases.
