### ISSUE TITLE
Math is not rendered

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysisTutorial#13]
The Mathjax code is not properly rendered. See, for example https://www.mdanalysis.org/MDAnalysisTutorial/trajectories.html#exercises-4
```
Take the functions to calculate \(\theta_\text{NMP}\) and \(\theta_\text{LID}\)
```

**Comment by kain88-de** [comment]
Math Jax changed its hosting to cloudflare. If we change where we pull the JavaScript from it should work again

**Comment by orbeckst** [comment]
I think we did this on the docs a while back but I only noticed the other day on the tutorial and I added the issue lest I forget.

**Comment by orbeckst** [comment]
I just checked: we are already using the cloudflare MathJax. Well, it's working  for me. Perhaps I forgot to allow the appropriate javascript (through noscript).
