### ISSUE TITLE
Convert to python 3

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/MDAnalysisTutorial#15]
When MDAnalysis 0.17 will be release, it will be possible to convert the tutorial to python 3. I expect the conversion to involve only little changes for the users; we probably want notes about things that would differ between versions of python (mostly `print` and `zip`).

**Comment by orbeckst** [comment]
We should then also make 0.17.0 the required version for the tutorial and update the major release of the tutorial.

**Comment by richardjgowers** [comment]
@jbarnoud I think py3 is the "official" version now in 0.17 anyway, so this can be done asap
