### ISSUE TITLE
add conda installation instructions

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysisTutorial#7]
With MDAnalysis available through `conda` (MDAnalysis/mdanalysis#608) and the blog post announcement imminent (MDAnalysis/MDAnalysis.github.io#20), we should also update the tutorial to provide the conda-based installation as a simple starting point.

**Comment by orbeckst** [comment]
@kain88-de if you don't want to do it, un-assign yourself.

**Comment by kain88-de** [comment]
Not sure when I will get to it. But that shouldn't be to much of a change.
